# You can use it to add commands that run after login to macOS user session.
# 'start-at-login' needs to be 'true' for 'after-login-command' to work
# Available commands: https://nikitabobko.github.io/AeroSpace/commands
after-login-command = []

# You can use it to add commands that run after AeroSpace startup.
# 'after-startup-command' is run after 'after-login-command'
# Available commands : https://nikitabobko.github.io/AeroSpace/commands
after-startup-command = []

# Start AeroSpace at login
start-at-login = true

# Move windows by dragging any part of the window
# https://nikitabobko.github.io/AeroSpace/goodies#move-by-dragging-any-part-of-the-window
# exec-and-forget = defaults write -g NSWindowShouldDragOnGesture -bool true

# Normalizations. See: https://nikitabobko.github.io/AeroSpace/guide#normalization
enable-normalization-flatten-containers = true
enable-normalization-opposite-orientation-for-nested-containers = true

# See: https://nikitabobko.github.io/AeroSpace/guide#layouts
# The 'accordion-padding' specifies the size of accordion padding
# You can set 0 to disable the padding feature
accordion-padding = 0

# Possible values: tiles|accordion
default-root-container-layout = 'tiles'

# Possible values: horizontal|vertical|auto
# 'auto' means: wide monitor (anything wider than high) gets horizontal orientation,
#               tall monitor (anything higher than wide) gets vertical orientation
default-root-container-orientation = 'auto'

# Mouse follows focus when focused monitor changes
# Drop it from your config, if you don't like this behavior
# See https://nikitabobko.github.io/AeroSpace/guide#on-focus-changed-callbacks
# See https://nikitabobko.github.io/AeroSpace/commands#move-mouse
# Fallback value (if you omit the key): on-focused-monitor-changed = []
on-focused-monitor-changed = ['move-mouse monitor-lazy-center']

# You can effectively turn off macOS "Hide application" (cmd-h) feature by toggling this flag
# Useful if you don't use this macOS feature, but accidentally hit cmd-h or cmd-alt-h key
# Also see: https://nikitabobko.github.io/AeroSpace/goodies#disable-hide-app
automatically-unhide-macos-hidden-apps = true

# Disable annoying and useless "hide application" shortcut
# https://nikitabobko.github.io/AeroSpace/goodies#disable-hide-app
cmd-h = [] # Disable "hide application"
cmd-alt-h = [] # Disable "hide others"

# Possible values: (qwerty|dvorak)
# See https://nikitabobko.github.io/AeroSpace/guide#key-mapping
[key-mapping]
    preset = 'qwerty'

# Gaps between windows (inner-*) and between monitor edges (outer-*).
# Possible values:
# - Constant:     gaps.outer.top = 8
# - Per monitor:  gaps.outer.top = [{ monitor.main = 16 }, { monitor."some-pattern" = 32 }, 24]
#                 In this example, 24 is a default value when there is no match.
#                 Monitor pattern is the same as for 'workspace-to-monitor-force-assignment'.
#                 See:
#                 https://nikitabobko.github.io/AeroSpace/guide#assign-workspaces-to-monitors
[gaps]
    inner.horizontal = 10
    inner.vertical = 10
    outer.left = 12
    outer.bottom = 12
    outer.top = 12
    outer.right = 12

# 'main' binding mode declaration
# See: https://nikitabobko.github.io/AeroSpace/guide#binding-modes
# 'main' binding mode must be always presented
# Fallback value (if you omit the key): mode.main.binding = {}
[mode.main.binding]

    # All possible keys:
    # - Letters.        a, b, c, ..., z
    # - Numbers.        0, 1, 2, ..., 9
    # - Keypad numbers. keypad0, keypad1, keypad2, ..., keypad9
    # - F-keys.         f1, f2, ..., f20
    # - Special keys.   minus, equal, period, comma, slash, backslash, quote, semicolon,
    #                   backtick, leftSquareBracket, rightSquareBracket, space, enter, esc,
    #                   backspace, tab
    # - Keypad special. keypadClear, keypadDecimalMark, keypadDivide, keypadEnter, keypadEqual,
    #                   keypadMinus, keypadMultiply, keypadPlus
    # - Arrows.         left, down, up, right

    # All possible modifiers: cmd, alt, ctrl, shift

    # All possible commands: https://nikitabobko.github.io/AeroSpace/commands

    # See: https://nikitabobko.github.io/AeroSpace/commands#exec-and-forget
    # You can uncomment the following lines to open up terminal with alt + enter shortcut
    # (like in i3)
    # alt-enter = '''exec-and-forget osascript -e '
    # tell application "Terminal"
    #     do script
    #     activate
    # end tell'
    # '''


    # See: https://nikitabobko.github.io/AeroSpace/commands#focus
    alt-h = 'focus left'
    alt-j = 'focus down'
    alt-k = 'focus up'
    alt-l = 'focus right'
    # alt-left = 'focus left'
    # alt-down = 'focus down'
    # alt-up = 'focus up'
    # alt-right = 'focus right'

    # See: https://nikitabobko.github.io/AeroSpace/commands#workspace
    alt-1 = 'workspace 1'
    alt-2 = 'workspace 2'
    alt-3 = 'workspace 3'
    alt-4 = 'workspace 4'
    alt-5 = 'workspace 5'
    alt-b = 'workspace b' # browser
    alt-c = 'workspace c' # chat
    alt-f = 'workspace f' # file explorer
    alt-t = 'workspace t' # terminal
    alt-m = 'workspace m' # mail

    # See: https://nikitabobko.github.io/AeroSpace/commands#move-node-to-workspace
    alt-shift-1 = 'move-node-to-workspace 1'
    alt-shift-2 = 'move-node-to-workspace 2'
    alt-shift-3 = 'move-node-to-workspace 3'
    alt-shift-4 = 'move-node-to-workspace 4'
    alt-shift-5 = 'move-node-to-workspace 5'
    alt-shift-b = 'move-node-to-workspace b' # browser
    alt-shift-c = 'move-node-to-workspace b' # chat
    alt-shift-f = 'move-node-to-workspace f' # file explorer
    alt-shift-m = 'move-node-to-workspace m' # mail
    alt-shift-t = 'move-node-to-workspace t' # terminal

    # See: https://nikitabobko.github.io/AeroSpace/commands#move
    alt-shift-h = 'move left'
    alt-shift-j = 'move down'
    alt-shift-k = 'move up'
    alt-shift-l = 'move right'
    # alt-shift-left = 'move left'
    # alt-shift-down = 'move down'
    # alt-shift-up = 'move up'
    # alt-shift-right = 'move right'

    # full
    alt-enter = 'macos-native-fullscreen'
    # alt-enter = 'fullscreen'

    # quick switch between workspaces
    alt-tab = 'workspace-back-and-forth'
    # alt-shift-tab = 'move-workspace-to-monitor --wrap-around next'
    ctrl-shift-tab = 'move-workspace-to-monitor --wrap-around next'

    # See: https://nikitabobko.github.io/AeroSpace/commands#layout
    # update current workspace layout
    # toggle between horizontal and vertical layout
    alt-slash = 'layout tiles horizontal vertical'
    # toggle between stack and tile layout
    alt-comma = 'layout accordion horizontal vertical'

    # [[on-window-detected]]
    #     if.app-id = 'org.mozilla.firefox'
    #     run = 'move-node-to-workspace b' # mnemonics B - Browser
    # [[on-window-detected]]
    #     if.app-id = 'com.mitchellh.ghostty'
    #     # if.app-name-regex-substring = 'ghostty'
    #     # mnemonics T - Terminal
    #     run = 'move-node-to-workspace t'

    # See: https://nikitabobko.github.io/AeroSpace/commands#workspace-back-and-forth
    # alt-tab = 'workspace-back-and-forth'
    # See: https://nikitabobko.github.io/AeroSpace/commands#move-workspace-to-monitor
    # alt-shift-tab = 'move-workspace-to-monitor --wrap-around next'

    # Modes. See: https://nikitabobko.github.io/AeroSpace/commands#mode
    # From main mode to service mode
    alt-shift-semicolon = 'mode service'
    # From main mode to resize mode
    alt-r = 'mode resize'      # 1. Define a binding to switch to 'resize' mode


# 'resize' binding mode declaration.
[mode.resize.binding]          # 2. Declare 'resize' binding mode
    # See: https://nikitabobko.github.io/AeroSpace/commands#resize
    up = 'resize smart +50'
    down = 'resize smart +50'
    left = 'resize smart -50'
    right = 'resize smart +50'
    # alt-minus = 'resize smart -50'
    # alt-equal = 'resize smart +50'
    # shift-right = 'resize width -10'
    # shift-left = 'resize width height +10'
    # shift-up = 'resize up +10'
    # shift-down = 'resize height +10'
    # alt-minus = 'resize width -10'
    # alt-equal = 'resize width +10'
    # alt-shift-minus = 'resize height -10'
    # alt-shift-equal = 'resize height +10'

    # vim like bindings to resize
    h = 'resize width -50'
    j = 'resize height +50'
    k = 'resize height -50'
    l = 'resize width +50'
    shift-h = 'resize width -10'
    shift-j = 'resize height +10'
    shift-k = 'resize height -10'
    shift-l = 'resize width +10'

    # back to main mode
    esc = 'mode main'
    enter = 'mode main'


# 'service' binding mode declaration.
# See: https://nikitabobko.github.io/AeroSpace/guide#binding-modes
[mode.service.binding]
    esc = ['reload-config', 'mode main']
    r = ['flatten-workspace-tree', 'mode main'] # reset layout
    f = ['layout floating tiling', 'mode main'] # Toggle between floating and tiling layout
    backspace = ['close-all-windows-but-current', 'mode main']

    # sticky is not yet supported https://github.com/nikitabobko/AeroSpace/issues/2
    #s = ['layout sticky tiling', 'mode main']

    # alt-shift-h = ['join-with left', 'mode main']
    # alt-shift-j = ['join-with down', 'mode main']
    # alt-shift-k = ['join-with up', 'mode main']
    # alt-shift-l = ['join-with right', 'mode main']

    # volume
    # down = 'volume down'
    # up = 'volume up'
    shift-down = ['volume set 0', 'mode main']
